networks:
  dev:
    driver: bridge

services:

  backend:
    image: backend-service:latest
    container_name: backend-service
    ports:
      - 5001:5001
    environment:
      - ASPNET_ENVIROMENT=Developement
    depends_on:
      - "db"
    networks:
      - dev

  frontend-app:
    image: client-front-end:latest
    networks:
      - dev
    ports:
      - 8000:80

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis  

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
     - 5432:5432
    networks:
     - dev
    volumes:
      - app-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    networks:
     - dev
    ports:
     - 8080:8080
     
volumes:
  redis-data:
  app-data: